type IconNames =
    | 'lightning'
    | 'list'
    | 'logo'
    | 'phone-c'
    | 'profile'
    | 'savings'
    | 'stats'
    | 'star'
    | 'support'
    | 'account'
    | 'address'
    | 'arrowdown'
    | 'arrowleft'
    | 'arrowright'
    | 'arrowup'
    | 'burger'
    | 'cart'
    | 'clock-c'
    | 'close'
    | 'done'
    | 'edit'
    | 'email'
    | 'email-c'
    | 'facebook'
    | 'find'
    | 'grid'
    | 'heart'
    | 'instagram'

export default IconNames
